language: python
python:
  - "2.7"
    
install:
  - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

script:
  - export PLATFORMIO_LIB_DIR=$PWD
  - echo $PLATFORMIO_LIB_DIR
  - platformio ci example/Benchmark/Benchmark.ino  --board=uno --board=megaatmega1280 
  - platformio ci example/Callback/Callback.ino  --board=uno --board=megaatmega1280 
  - platformio ci example/DataOverSerial/DataOverSerial.ino  --board=uno --board=megaatmega1280 
  - platformio ci example/SignalPower/SignalPower.ino  --board=uno --board=megaatmega1280 
  - platformio ci example/Velocity/Velocity.ino  --board=uno --board=megaatmega1280 
notifications: 
  email:
    on_success: change
    on_failure: change