language: python
python:
  - "2.7"
    
install:
  - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
  - 
script:
  - echo `platformio lib --global install file:///$PWD || \`
  - platformio ci --lib="." example/Benchmark/Benchmark.ino  --board=uno --board=megaatmega1280 
  - platformio ci --lib="." example/Callback/Callback.ino  --board=uno --board=megaatmega1280 
  - platformio ci --lib="." example/DataOverSerial/DataOverSerial.ino  --board=uno --board=megaatmega1280 
  - platformio ci --lib="." example/SignalPower/SignalPower.ino  --board=uno --board=megaatmega1280 
  - platformio ci --lib="." example/Velocity/Velocity.ino  --board=uno --board=megaatmega1280 
notifications: 
  email:
    on_success: change
    on_failure: change